/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:937a9fec-2a5b-4849-b2dd-5a38e646e034",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_40hzWccRq",
    "aws_user_pools_web_client_id": "328df6si68rgrbr5qqpb2kq6ms",
    "oauth": {}
};


export default awsmobile;
